# Introducción {#intro}

El Centro Mexicano de Innovación en Energía Océano (CEMIE-Océano), reune a un número importante de centros de investigación. Su misión es generar productos, técnicas y tecnologías innovadoras que exploten la diversidad de recursos energéticos océanicos disponibles para suministrar de manera sustentable y rentable una parte cada vez mayor de la demanda energética de la República Mexicana.

Desde su creación, hace más de dos años, el CEMIE-Océano ha generado una gran cantidad de información, producto de las investigaciones y trabajos realizados. Esta información debe ser divulgada para permitir la vinculación entre los generadores de información con sectores de índole económica o industrial. Por la naturaleza de la información generada, gran cantidad de ésta puede ser presentada como libros tipo atlas.
<!-- Comentario para probar algo -->

## Subsección para incluir referencias

En el objetivo se hace referencia a *libros con contenidos gráficos y numéricos en forma de atlas interactivos*, lo que es una especialización del concepto más general: *libros digitales interactivos*. El concepto de libros interactivos tiene su origen en los libros *pop-up* para niños, creados por Julian Wehr en la década de 1940 [@MBS2002; @Bohem2002]. Estos libros tangibles, permiten a los niños interactuar con su contenido, mediante el accionar de las pestañas de papel o cartón, provistas en el libro para *animar* o dar movilidad a las ilustraciones, tal como el que se muestra en la animación de abajo. Más tarde, con el advenimiento de los libros digitales o electrónicos, los portales *Web* y los libros en línea [@Reilly2003], la idea de que los lectores pudieran interactuar con su contenido permeó de los libros tangibles a los libros digitales en línea.

